name: Auto-build

on: [push, workflow_dispatch]

jobs:
  compile_static:
    runs-on: windows-latest
    steps:
      - uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
      - uses: anthepro/install-qt-static@v1
        with:
          version: 6.7.2
          configure-args: -opensource -opengl desktop
          submodules: defaults
          dir: C:/qt-static/
      -
        name: Checkout
        uses: actions/checkout@v2
        with: 
          submodules : true
      -
        name: build
        run: |
          C:/qt-static/bin/qmake.exe WorldConv.pro -spec win64-msvc "CONFIG+=release" "CONFIG+=static"