name: Auto-build

on: [push, pull_request, workflow_dispatch]

jobs:        

  linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    strategy:
        matrix:
            build_type: ["Release", "Debug"]
    steps:

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        host: 'windows'
        target: 'desktop'
        set-env: 'true'
    - uses: actions/checkout@v3
    - name: Compile with GCC
      run: |
        cmake . -B build
        cmake --build build --config ${{ matrix.build_type }}
      shell: bash
    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: GCC_DLL_${{ matrix.build_type }}
        path: |
          ${{ github.workspace }}/build/WorldConv
